name: nightly-update

# ── Permissions ────────────────────────────────────────────────
# Allow the workflow to commit the refreshed CSV files back
permissions:
  contents: write        # <-- required for stefanzweifel/git-auto-commit-action

# ── When to run ────────────────────────────────────────────────
on:
  schedule:              # every day 10:30 UTC ≈ 3:30 AM Phoenix
    - cron: '30 10 * * *'
  workflow_dispatch:     # adds a “Run workflow” button in GitHub UI

# ── What to run ────────────────────────────────────────────────
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out repo
    - uses: actions/checkout@v4

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3. Install libraries
    - name: Install libraries
      run: |
        python -m pip install --upgrade pip
        pip install pybaseball pandas --quiet

    # 4. Run the updater script
    - name: Run updater
      run: python update_pitchers.py

    # 5. Commit updated CSVs back to the repo
    - name: Commit updated CSVs
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Nightly auto-update"
